# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55a6913bad009bf1c716b28d57d848ae04e82fb9c7270b8f9d80b4a44ad42723df254d515aeb913d560dfe3b78e5ed6ac42d8a11ed65520e68bcaf7c5c0b326

test:
  secret_key_base: 89a6fb65fe96b5e9ffd1cc5979a4cf8c380071e4db864d32f973f92061ee1a167aecde41f679b42364f1c934b60ca7b2d76a45f8c404dfac74969c5c805428b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
